[keys]
prefix = 'ctrl+f'
goto = 'prefix+s'
last_pane = 'prefix+ctrl+o'
navigate_workspace_down = 'j'
navigate_workspace_up = 'k'
next_agent = 'prefix+ctrl+]'
previous_agent = 'prefix+ctrl+['
settings = 'prefix+shift+s'
split_horizontal = 'prefix+v'
split_vertical = 'prefix+\'
zoom = 'prefix+m'

[ui]
prompt_new_tab_name = false
pane_gaps = false

[ui.toast]
delivery = "system"

[theme]
name = "catppuccin"
auto_switch = false

[experimental]
switch_ascii_input_source_in_prefix = true

# https://github.com/hotchpotch/herdr-tiny-fingers
[[keys.command]]
key = "prefix+y"
type = "plugin_action"
command = "hotchpotch.herdr-tiny-fingers.open"
description = "fingers mode"
