alias g="git"
alias ga="git add"
alias ga.="git add ."
alias gd="git diff"
alias gdw="git diff -w"
alias gs="git status"
alias gp="git push"
alias gpu="git pull"
alias gprune="git pull --prune"
alias gb="git branch"
alias gc="git commit -m"
alias gcv="git commit -v"
alias gcf="git commit --fixup"
alias gca="git commit -am"
alias gamend="DISABLE_INSERT=true git commit --amend"
alias gch="git checkout"
alias gchb="git checkout -B"
alias gl="git log"
alias gf="git fetch"
alias gm="git merge"
alias gr="git reset"
alias gr:s="git reset --soft HEAD^"
alias gr:h="git reset --hard HEAD^"
alias gcl="git clone"
alias gres="git restore"
alias grb="git rebase"
alias grbi="git rebase -i"
alias gcp="git cherry-pick"

alias remote="gh repo view --web"
alias repo="gh repo view --web"
alias pr="gh pr view -w"
alias prn="gh pr create"
alias prnf="gh pr create -f"

alias wip="git commit -m 'WIP'"
alias wipa="git add . && wip"
