[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'fannheyward/telescope-coc.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_event = 'VimEnter'
depends = ['plenary.nvim', 'telescope-coc.nvim', 'telescope-fzf-native.nvim']
hook_source = 'exec "source" stdpath("config") . "/plugins/telescope.lua"'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = 'VimEnter'
hook_source = 'exec "source" stdpath("config") . "/plugins/gitsigns.nvim.lua"'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = 'VimEnter'
hook_post_update = 'TSUpdate'
hook_source = 'exec "source" stdpath("config") . "/plugins/nvim-treesitter.lua"'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'romgrk/nvim-treesitter-context'
on_source = 'nvim-treesitter'
hook_source = 'exec "source" stdpath("config") . "/plugins/nvim-treesitter-context.lua"'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_source = 'nvim-treesitter'

# [[plugins]]
# repo = 'nvim-treesitter/playground'
# on_source = 'nvim-treesitter'

[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'CursorHold'

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
on_cmd = 'FuzzyMotion'
hook_source = 'exec "source" stdpath("config") . "/plugins/fuzzy-motion.vim"'
depends = ['denops.vim']

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'lambdalisue/kensaku-search.vim'
on_event = 'CursorHold'
hook_source = 'cnoremap <CR> <Plug>(kensaku-search-replace)<CR>'
depends = ['kensaku.vim']

[[plugins]]
repo = 'itchyny/vim-qfedit'
on_ft = ['qf']

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'VimEnter'
hook_source = 'exec "source" stdpath("config") . "/plugins/nvim-autopairs.lua"'

[[plugins]]
repo = 'folke/todo-comments.nvim'
on_event = 'VimEnter'
hook_source = 'exec "source" stdpath("config") . "/plugins/todo-comments.nvim.lua"'

[[plugins]]
repo = 'numToStr/Comment.nvim'
on_event = 'BufRead'
hook_source = 'exec "source" stdpath("config") . "/plugins/comment.nvim.lua"'

[[plugins]]
repo = 'akinsho/git-conflict.nvim'
rev = '*'
on_event = 'BufRead'
hook_source = '''
exec "source" stdpath("config") . "/plugins/git-conflict.nvim.lua"
exec "source" stdpath("config") . "/plugins/git-conflict.nvim.vim"
'''

[[plugins]]
repo = 'dmmulroy/tsc.nvim'
on_ft = ['typescript', 'typescriptreact']
hook_source = 'exec "source" stdpath("config") . "/plugins/tsc.nvim.lua"'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
rev = '*'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'
hook_source = 'exec "source" stdpath("config") . "/plugins/markdown-preview.vim"'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'iloginow/vim-stylus'
on_ft = ['stylus']

[[plugins]]
repo = 'mkobayashime/vim-stylus-supremacy'
on_ft = ['stylus']

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
on_event = 'BufReadPost'
hook_source = 'exec "source" stdpath("config") . "/plugins/nvim-scrollbar.lua"'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
on_event = 'BufReadPost'
hook_source = 'exec "source" stdpath("config") . "/plugins/indent-blankline.nvim.lua"'
