#!/usr/bin/env bash

for FILE in "$@"; do
  if [[ -e "$FILE" ]]; then
    case $FILE in
      *.BAK) ;;

      *.bak) ;;

      *)
        mv "$FILE" "$FILE.BAK"
        ;;
    esac
  else
    echo "$FILE not found"
  fi
done
