#!/usr/bin/env bash

set -euo pipefail

branches=$(git branch -vv | grep '^[^*]')
branch=$(echo "$branches" | fzf --ansi | awk '{print $1}' | sed "s/.* //")
if [[ "$branch" != '*' ]] && [[ "$branch" ]]; then
  git switch "$branch"
fi
