#!/usr/bin/env bash

usage() {
  cat << EOL
OPTIONS
  -f, --full-hash
  -h, --help

EXAMPLE
  fgl 10
    - Search recent 10 commits and outputs the abbr hash
  fgl 100 -f
    - Search recent 100 commits and outputs the full hash
EOL
}

if [[ ! -d '.git' ]]; then
  echo "Not in a git directory" 1>&2
  exit 1
fi

for OPT in "$@"; do
  case $OPT in
    -h | --help)
      usage
      exit 0
      ;;
    -f | --full-hash)
      full_hash=true
      shift 1
      ;;
    -*)
      echo "Unknown option: $1" 1>&2
      exit 1
      ;;
    *)
      commit_count=$1
      shift 1
      ;;
  esac
done

if [[ "$commit_count" == '' ]]; then
  commit_count=100
elif [[ "$commit_count" =~ ^[0-9]+$ ]]; then
  :
else
  echo 'NaN passed as commit count' 1>&2
  exit 1
fi

commit=$(git log --oneline -$commit_count | fzf --ansi)
hash_abbr=$(echo "$commit" | awk '{print $1}' | sed "s/.* //")

if [[ "$full_hash" == true ]]; then
  git log -1 --pretty='%H' "$hash_abbr"
else
  echo "$hash_abbr"
fi
