#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat << EOL
OPTIONS
  -f, --full-hash
  -h, --help

EXAMPLE
  fgl 10
    - Search recent 10 commits and outputs the abbr hash
  fgl 100 -f
    - Search recent 100 commits and outputs the full hash
EOL
}

for OPT in "$@"; do
  case $OPT in
    -h | --help)
      usage
      exit 0
      ;;
    -f | --full-hash)
      full_hash=true
      shift 1
      ;;
    -*)
      echo "Unknown option: $1" 1>&2
      exit 1
      ;;
    *)
      commit_count=${1:-}
      shift 1
      ;;
  esac
done

commit_count=${commit_count:-100}
if [[ ! "$commit_count" =~ ^[0-9]+$ ]]; then
  echo 'NaN passed as commit count' 1>&2
  exit 1
fi

commits=$(git log --oneline -"$commit_count")
commit=$(echo "$commits" | fzf --ansi)
hash_abbr=$(echo "$commit" | awk '{print $1}' | sed "s/.* //")

if [[ "${full_hash:-false}" == true ]]; then
  git log -1 --pretty='%H' "$hash_abbr"
else
  echo "$hash_abbr"
fi
