#!/bin/bash

# originally from https://gist.github.com/thugcee/41d1ba786fa5e66167ed6ee45e4f6346
# Fuzzy Tmux PANE

set -euo pipefail

# customizable
LIST_DATA=${FTPANE_LIST_DATA:-"#{window_name} #{pane_title} #{pane_current_path} #{pane_current_command}"}
FZF_COMMAND=${FTPANE_FZF_COMMAND:-"fzf-tmux -p --delimiter=: --with-nth 4 --color=hl:2"}

# do not change
TARGET_SPEC="#{session_name}:#{window_id}:#{pane_id}:"

LINE=$(tmux list-panes -a -F "$TARGET_SPEC $LIST_DATA" | $FZF_COMMAND) || exit 0
args=(${LINE//:/ })
tmux select-pane -t ${args[2]} && tmux select-window -t ${args[1]} && tmux switch-client -t ${args[0]}
