#!/usr/bin/env bash

set -euo pipefail

file=$(mktemp)

git symbolic-ref --short HEAD > "$file"
echo -e "\n\n" >> "$file"
echo "# Empty line 1 to cancel" >> "$file"
"${EDITOR:-vim}" "$file"

bname=$(head -n 1 "$file")
if [[ ! "$bname" ]]; then
  exit 0
else
  git branch -m "$bname"
fi

rm "$file"

exit 0
