#!/usr/bin/env bash

set -euo pipefail

BOLD=$(tput bold)
UNDERLINE=$(tput smul)
NORMAL=$(tput sgr0)

cmd=$(basename "$0")

description=

echoerr() {
  echo "${1:-}" 1>&2
}

usage() {
  cat << EOF
${BOLD}USAGE:${NORMAL}
  $cmd [-d ${UNDERLINE}DESCRIPTION_TEXT${NORMAL}] [${UNDERLINE}FILE...${NORMAL}]
  $cmd --help

${BOLD}OPTIONS:${NORMAL}
  ${BOLD}-d, --description${NORMAL} ${UNDERLINE}DESCRIPTION_TEXT${NORMAL}
    Set this text to images as description

  ${BOLD}-h, --help${NORMAL}
    Show this message
EOF
}

for OPT in "$@"; do
  case $OPT in
    -h | --help)
      usage
      exit 0
      ;;
    -d | --description)
      description=${2:-}
      shift 2
      ;;
    -*)
      echo "Unknown option: $1" 1>&2
      exit 1
      ;;
  esac
done

if [[ ! "$description" ]]; then
  echoerr "Fatal: Missing description text"
  echo
  usage
  exit 1
fi

exiftool -overwrite_original -IPTC:Caption-Abstract="$description" "$@"
