#!/usr/bin/env bash

set -euo pipefail

cmd=$(basename "$0")

description=

echoerr() {
  echo "${1:-}" 1>&2
}

usage() {
  cat << EOF
USAGE:
  $cmd -d [description_text] FILE...
EOF
}

for OPT in "$@"; do
  case $OPT in
    -h | --help)
      usage
      exit 0
      ;;
    -d | --description)
      description=${2:-}
      shift 2
      ;;
    -*)
      echo "Unknown option: $1" 1>&2
      exit 1
      ;;
  esac
done

if [[ ! "$description" ]]; then
  echoerr "Fatal: Missing description text"
  echo
  usage
  exit 1
fi

exiftool -overwrite_original -IPTC:Caption-Abstract="$description" "$@"
