#!/usr/bin/env bash

set -euo pipefail

list=$(mktemp)

trap '{ rm -f "$list" ; }' EXIT

if [[ -f joined.mp4 ]]; then
  echo -n 'joined.mp4 already exists. Overwrite? [y/N] '
  read -r overwrite
  [[ "$overwrite" != 'y' ]] && exit 0
fi

IFS=$'\n'

for f in "$@"; do
  echo "file '$(realpath $f)'" >> "$list"
done

unset IFS

ffmpeg -f concat -safe 0 -i "$list" -c copy joined.mp4
