#!/usr/bin/env bash

recent_commit=$(git log --format="%s" -1)

if [[ "$recent_commit" == "WIP" ]] || [[ "$recent_commit" == "WIP [skip ci]" ]]; then
  git reset --soft HEAD^ && git restore --staged .
else
  exit 1
fi
