#!/usr/bin/env bash

set -euo pipefail

source=${1:-}

if [[ ! "$source" ]]; then
  cat << ERR
Source zip file not provided.

USAGE:
    unziptodir <source.zip>
ERR
  exit 1
fi

filename=$(trimext "$source")
filedir=$(dirname "$source")

if [[ ! "$filename" ]] || [[ ! -d "$filedir" ]]; then
  echo "Failed to get where to unzip." 1>&2
  exit 1
fi

destdir="$filedir/$filename"

if [[ -e "$destdir" ]]; then
  echo -n "$destdir already exists. Overwrite? [y/N] "
  read -r overwrite
  [[ "$overwrite" != 'y' ]] && exit 0
fi

mkdir -p "$destdir"

unzip -o "$source" -d "$destdir"

files_in_dest_output=$(fd --max-depth 1 -H '' "$destdir")
mapfile -t files_in_dest <<< "$files_in_dest_output"

if [[ "${#files_in_dest[@]}" == 1 ]] && [[ -d "${files_in_dest[0]}" ]]; then
  inner_dir_in_dest=$(basename "${files_in_dest[0]}")
  inner_dir_in_dest_tmp="__TMP_$inner_dir_in_dest"

  echo "The zip has a top level directory: $inner_dir_in_dest"
  echo "Moving the files inside to the destination..."

  cd "$destdir"

  mv "$inner_dir_in_dest" "$inner_dir_in_dest_tmp"

  shopt -s dotglob
  mv -- "$inner_dir_in_dest_tmp"/* .

  rmdir "$inner_dir_in_dest_tmp"
fi
