live_config_reload = true

[colors.bright]
black = "#c2c7cf"
blue = "#1081d6"
cyan = "#0f7ddb"
green = "#1dd361"
magenta = "#5350b9"
red = "#de352e"
white = "#ffffff"
yellow = "#f3bd09"

[colors.normal]
black = "#1f1f1f"
blue = "#2a84d2"
cyan = "#1081d6"
green = "#2dc55e"
magenta = "#4e5ab7"
red = "#f81118"
white = "#d6dbe5"
yellow = "#ecba0f"

[colors.primary]
background = "#000000"
foreground = "#d6dbe5"

[colors.selection]
background = "#434547"
text = "CellForeground"

[font]
size = 12

[font.normal]
family = "JetBrains Mono NL"

[window]
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 10
y = 5
