#!/usr/bin/env bun

import { parseArgs } from "node:util";

void (async () => {
	const { positionals } = parseArgs({
		args: process.argv.slice(2),
		allowPositionals: true,
	});

	const [url] = positionals;

	const tryFetch = async ({ url, count }: { url: string; count: number }) => {
		if (count > 19) {
			console.error("Error: Max number of redirection exceeded");
			return;
		}

		const response = await fetch(url, { redirect: "manual" });

		console.log(response.status, response.url);

		if (response.status.toString().startsWith("3")) {
			const location = response.headers.get("location");

			if (!location) {
				console.error("Error: No location header found");
				return;
			}

			tryFetch({ url: new URL(location, url).toString(), count: count + 1 });
		}
	};

	await tryFetch({ url, count: 0 });
})();
