[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'source ~/.config/nvim/plugins/onedark.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = 'source ~/.config/nvim/plugins/coc.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'fannheyward/telescope-coc.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim', 'telescope-coc.nvim', 'telescope-fzf-native.nvim']
hook_add = 'source ~/.config/nvim/plugins/telescope.lua'

[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['FixCursorHold.nvim']
hook_add = 'let g:fern#default_hidden = 1'

# fern.vim dependency as workaround for bug of Neovim
[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

# Unix shell commands like `:Move`/`:Rename`
[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'folke/todo-comments.nvim'
hook_add = 'source ~/.config/nvim/plugins/todo-comments.nvim.lua'

[[plugins]]
repo = 'rmagatti/alternate-toggler'
