[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'source ~/.config/nvim/plugins/onedark.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = 'source ~/.config/nvim/plugins/coc.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['FixCursorHold.nvim']
hook_add = 'let g:fern#default_hidden = 1'

# fern.vim dependency as workaround for bug of Neovim
[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = 'source ~/.config/nvim/plugins/vim-trailing-whitespace.vim'

# Unix shell commands like `:Move`/`:Rename`
[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'
depends = ['vim-textobj-user']

[[plugins]]
repo = 'beloglazov/vim-textobj-quotes'
depends = ['vim-textobj-user']

[[plugins]]
repo = 'Julian/vim-textobj-brace'
depends = ['vim-textobj-user']

[[plugins]]
repo = 'jceb/vim-textobj-uri'
depends = ['vim-textobj-user']

[[plugins]]
repo = 'rmagatti/alternate-toggler'

[[plugins]]
repo = 'chrisbra/csv.vim'
