[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'fannheyward/telescope-coc.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_event = 'VimEnter'
depends = ['plenary.nvim', 'telescope-coc.nvim', 'telescope-fzf-native.nvim']
hook_source = 'source ~/.config/nvim/plugins/telescope.lua'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = 'VimEnter'
hook_source = 'source ~/.config/nvim/plugins/gitsigns.nvim.lua'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = 'VimEnter'
hook_post_update = 'TSUpdate'
hook_source = 'source ~/.config/nvim/plugins/nvim-treesitter.lua'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'romgrk/nvim-treesitter-context'
on_source = 'nvim-treesitter'
hook_source = 'source ~/.config/nvim/plugins/nvim-treesitter-context.lua'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_ft = [
  'html',
  'javascript',
  'javascriptreact',
  'jsx',
  'markdown',
  'rescript',
  'svelte',
  'tsx',
  'typescript',
  'typescriptreact',
  'vue',
  'xml',
]

[[plugins]]
repo = 'nvim-treesitter/playground'
on_source = 'nvim-treesitter'

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = 'VimEnter'
hook_source = 'source ~/.config/nvim/plugins/nvim-autopairs.lua'

[[plugins]]
repo = 'folke/todo-comments.nvim'
on_event = 'VimEnter'
hook_source = 'source ~/.config/nvim/plugins/todo-comments.nvim.lua'

[[plugins]]
repo = 'numToStr/Comment.nvim'
on_event = 'BufRead'
hook_source = 'source ~/.config/nvim/plugins/comment.nvim.lua'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'

[[plugins]]
repo = 'iloginow/vim-stylus'
on_ft = ['stylus']

[[plugins]]
repo = 'mkobayashime/vim-stylus-supremacy'
on_ft = ['stylus']
