[tools]
"aqua:BurntSushi/ripgrep" = "15.2.0"
"aqua:LuaLS/lua-language-server" = "3.19.0"
"aqua:antonmedv/fx" = "39.2.0"
"aqua:cli/cli" = "2.97.0"
"aqua:dandavison/delta" = "0.19.2"
"aqua:jqlang/jq" = "1.8.2"
"aqua:junegunn/fzf" = "0.74.3"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:mvdan/sh" = "3.13.1"
"aqua:neovim/neovim" = "0.12.4"
"aqua:ogulcancelik/herdr" = "0.7.5"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:sharkdp/fd" = "10.4.2"
"aqua:tmux/tmux-builds" = "3.7b"
"aqua:tree-sitter/tree-sitter" = "0.26.12"
"conda:imagemagick" = "7.1.2_27"
"core:bun" = "1.4.0"
"core:deno" = "2.9.5"
"core:ffmpeg" = "8.1.2"
"core:node" = "26.7.0"
"github:yt-dlp/yt-dlp" = { version = "2026.07.04", rename_exe = "yt-dlp" }
"npm:@playwright/cli" = "0.1.18"
"npm:@tailwindcss/language-server" = "0.16.0"
"npm:bash-language-server" = "5.6.0"
"npm:cspell" = "10.0.1"
"npm:typescript-language-server" = "5.3.0"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.24.0"

[settings]
lockfile = true
minimum_release_age = "7d"
pin = true

[settings.npm]
package_manager = "bun"
